"""create post table

Revision ID: 363a15ebef23
Revises: 8c1a382f4ebd
Create Date: 2025-12-02 00:07:07.293728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363a15ebef23'
down_revision = '8c1a382f4ebd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('type', sa.Enum('text', 'image', 'video', 'news', name='post_type_enum'), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('source_name', sa.String(length=100), nullable=True),
        sa.Column('source_url', sa.String(length=255), nullable=True),
        sa.Column('author_name', sa.String(length=100), nullable=True),
        sa.Column('tags_cache', sa.JSON(), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('is_sensitive', sa.Boolean(), server_default='0', nullable=True),
        sa.Column('published_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_created', 'posts', ['created_at'], unique=False)
    op.create_index('idx_posts_user', 'posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_user', table_name='posts')
    op.drop_index('idx_posts_created', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
