"""create_user_auth_providers

Revision ID: 8c1a382f4ebd
Revises: 1a030c74d9e3
Create Date: 2025-11-30 21:29:24.623729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1a382f4ebd'
down_revision = '1a030c74d9e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth_providers_id'), 'user_auth_providers', ['id'], unique=False)
    op.create_index(op.f('ix_user_auth_providers_provider_user_id'), 'user_auth_providers', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_providers_provider_user_id'), table_name='user_auth_providers')
    op.drop_index(op.f('ix_user_auth_providers_id'), table_name='user_auth_providers')
    op.drop_table('user_auth_providers')
    # ### end Alembic commands ###
