"""create post_media table

Revision ID: a1b2c3d4e5f6
Revises: 363a15ebef23
Create Date: 2025-12-02 00:08:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '363a15ebef23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_media',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('media_type', sa.Enum('image', 'video', name='media_type_enum'), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('has_audio', sa.Boolean(), server_default='1', nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
        sa.Column('position', sa.Integer(), server_default='0', nullable=True),
        sa.Column('cdn_provider', sa.String(length=50), nullable=True),
        sa.Column('file_size_kb', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_post', 'post_media', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_media_post', table_name='post_media')
    op.drop_table('post_media')
    # ### end Alembic commands ###
