"""create post_bookmarks table

Revision ID: a2b3c4d5e6f7
Revises: f6a1b2c3d4e5
Create Date: 2025-12-02 00:14:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f7'
down_revision = 'f6a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_bookmarks',
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_index('idx_bookmarks_user_created', 'post_bookmarks', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookmarks_user_created', table_name='post_bookmarks')
    op.drop_table('post_bookmarks')
    # ### end Alembic commands ###
