"""create post_shares table

Revision ID: b3c4d5e6f7a8
Revises: a2b3c4d5e6f7
Create Date: 2025-12-02 00:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c4d5e6f7a8'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_shares',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('share_type', sa.String(length=20), nullable=False),
        sa.Column('target', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_shares_post', 'post_shares', ['post_id'], unique=False)
    op.create_index('idx_post_shares_user', 'post_shares', ['user_id'], unique=False)
    op.create_index('idx_post_shares_created', 'post_shares', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_shares_created', table_name='post_shares')
    op.drop_index('idx_post_shares_user', table_name='post_shares')
    op.drop_index('idx_post_shares_post', table_name='post_shares')
    op.drop_table('post_shares')
    # ### end Alembic commands ###
