"""create post_comments table

Revision ID: c4d5e6f7a8b9
Revises: b3c4d5e6f7a8
Create Date: 2025-12-02 00:16:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d5e6f7a8b9'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comments',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('parent_id', sa.String(36), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('likes_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_comments_id', 'post_comments', ['id'], unique=False)
    op.create_index('idx_post_comments_post', 'post_comments', ['post_id'], unique=False) # Added likely useful index
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_comments_post', table_name='post_comments')
    op.drop_index('idx_post_comments_id', table_name='post_comments')
    op.drop_table('post_comments')
    # ### end Alembic commands ###
