"""create post_metrics table

Revision ID: d4e5f6a1b2c3
Revises: c3d4e5f6a1b2
Create Date: 2025-12-02 00:11:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6a1b2c3'
down_revision = 'c3d4e5f6a1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_metrics',
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('likes_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('comments_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('shares_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('bookmarks_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_metrics')
    # ### end Alembic commands ###
