"""create comment_likes table

Revision ID: d5e6f7a8b9c0
Revises: c4d5e6f7a8b9
Create Date: 2025-12-02 00:17:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e6f7a8b9c0'
down_revision = 'c4d5e6f7a8b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
        sa.Column('comment_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('idx_comment_likes_user', 'comment_likes', ['user_id'], unique=False)
    op.create_index('idx_comment_likes_comment_created', 'comment_likes', ['comment_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comment_likes_comment_created', table_name='comment_likes')
    op.drop_index('idx_comment_likes_user', table_name='comment_likes')
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
