"""create post_scores table

Revision ID: e5f6a1b2c3d4
Revises: d4e5f6a1b2c3
Create Date: 2025-12-02 00:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6a1b2c3d4'
down_revision = 'd4e5f6a1b2c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_scores',
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('engagement_score', sa.Float(), server_default='0', nullable=True),
        sa.Column('freshness_score', sa.Float(), server_default='0', nullable=True),
        sa.Column('quality_score', sa.Float(), server_default='0', nullable=True),
        sa.Column('spam_score', sa.Float(), server_default='0', nullable=True),
        sa.Column('report_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('last_computed_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_scores')
    # ### end Alembic commands ###
