"""create post_likes table

Revision ID: f6a1b2c3d4e5
Revises: e5f6a1b2c3d4
Create Date: 2025-12-02 00:13:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a1b2c3d4e5'
down_revision = 'e5f6a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
        sa.Column('post_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
        sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_index('idx_post_likes_user', 'post_likes', ['user_id'], unique=False)
    op.create_index('idx_post_likes_post_created', 'post_likes', ['post_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_likes_post_created', table_name='post_likes')
    op.drop_index('idx_post_likes_user', table_name='post_likes')
    op.drop_table('post_likes')
    # ### end Alembic commands ###
